/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DTO.Congnhan;
import DTO.NhanVien;
import Dao.CongNhanDao;
import Dao.nhanviendao;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang Pham
 */
public class QuanLyNhanVien extends javax.swing.JPanel {
private DefaultTableModel tblmodel;
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        initTable();
        loadTable();
    }
 private void initTable()
    {
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[] {"ID","Họ tên", "Năm sinh", "Giới tính", "Địa chỉ","Công việc"});
        jTable1.setModel(tblmodel);
    }
    private void loadTable()
    {
        try
        {
            nhanviendao dao = new nhanviendao();
            List<NhanVien> list = dao.hienthi(txthoten.getText());            
            tblmodel.setRowCount(0);
            for(NhanVien cn : list)
            {
                tblmodel.addRow(new Object[]{cn.getId(),cn.getHoten(), cn.getNgaysinh(),
                    cn.getGioitinh()==1?"Nam":"Nữ", cn.getDiachi(), cn.getCongviec()});
            }
            tblmodel.fireTableDataChanged();
             }catch(Exception e)
        {
            e.printStackTrace();
           
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtcongviec = new javax.swing.JTextField();
        rbdnam = new javax.swing.JRadioButton();
        rbdnu = new javax.swing.JRadioButton();
        btntimkiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntaomoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtidchucvu = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý nhân viên");

        jLabel2.setText("ID:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Công việc:");

        txthoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbdnam);
        rbdnam.setText("Nam");

        buttonGroup1.add(rbdnu);
        rbdnu.setText("Nữ");

        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass.png"))); // NOI18N
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/insert.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/updated.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntaomoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eraser.png"))); // NOI18N
        btntaomoi.setText("Tạo mới");
        btntaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaomoiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtidchucvu.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel2)
                                .addGap(75, 75, 75)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rbdnam)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rbdnu)
                                                    .addGap(44, 44, 44))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtcongviec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(36, 36, 36)
                                            .addComponent(txtngaysinh))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(51, 51, 51)
                                            .addComponent(txthoten)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(btnThem)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsua)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnxoa)
                                    .addGap(30, 30, 30)
                                    .addComponent(btntaomoi)
                                    .addGap(18, 18, 18)
                                    .addComponent(btntimkiem)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbdnam)
                    .addComponent(rbdnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btntaomoi)
                    .addComponent(btntimkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void clearform()
{
    txttimkiem.setText("");
    txthoten.setText("");
    txtngaysinh.setText("");
    buttonGroup1.clearSelection();
    txtdiachi.setText("");
    txtcongviec.setText("");
}
    private void txthotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txthoten.getText().equals("")){
             sb.append("Ho ten không được để trống \n");
        txthoten.setBackground(Color.red);
        }else
        {
            txthoten.setBackground(Color.white);
        }
        if(txtngaysinh.getText().equals("")){
             sb.append("Ngày sinh không được để trống \n");
        txtngaysinh.setBackground(Color.red);
        }else
        {
            txtngaysinh.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error" , JOptionPane.ERROR_MESSAGE);
        return;
        }
         int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?","Hỏi",
        JOptionPane.YES_OPTION );
        if(choice == JOptionPane.NO_OPTION)
            return;
        
       NhanVien cn = new NhanVien();
        
            
            cn.setHoten(txthoten.getText());
            try{
            cn.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").parse(txtngaysinh.getText())); 
            
            }catch(Exception e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Định dạng ngày phải nập đúng theo mẫu yyyy-MM-dd!");
            }
            cn.setGioitinh(rbdnam.isSelected()?1 : 0);
            cn.setDiachi(txtdiachi.getText());
            cn.setCongviec(txtcongviec.getText());
            
            cn.setIdchucvu(Integer.parseInt(txtidchucvu.getText()));
//            cn.setIdchucvu(txtidchucvu);
           
         nhanviendao dao = new nhanviendao();
         try {
            if(dao.them(cn))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                clearform();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
           StringBuilder sb = new StringBuilder();
        if(txttimkiem.getText().equals("")){
             sb.append("id không được để trống \n");
        
        }else
        {
            txttimkiem.setBackground(Color.white);
        }
      if(txthoten.getText().equals("")){
             sb.append("Ho ten không được để trống \n");
        txthoten.setBackground(Color.red);
        }else
        {
            txthoten.setBackground(Color.white);
        }
        if(txtngaysinh.getText().equals("")){
             sb.append("Ngày sinh không được để trống \n");
        txtngaysinh.setBackground(Color.red);
        }else
        {
            txtngaysinh.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error" , JOptionPane.ERROR_MESSAGE);
        return;
        }
         int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn Sửa không?","Hỏi",
        JOptionPane.YES_OPTION );
        if(choice == JOptionPane.NO_OPTION)
            return;
        
        NhanVien cn = new NhanVien();
        
            cn.setId(txttimkiem.getText());
            cn.setHoten(txthoten.getText()); 
            try{
            cn.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").parse(txtngaysinh.getText())); 
             
            }catch(Exception e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Định dạng ngày phải nập đúng theo mẫu yyyy-MM-dd!");
            }
            cn.setGioitinh(rbdnam.isSelected()?1 : 0);
            cn.setDiachi(txtdiachi.getText());
            cn.setCongviec(txtcongviec.getText());            
            cn.setIdchucvu(Integer.parseInt(txtidchucvu.getText()));
//            cn.setIdchucvu(txtidchucvu);
           
        nhanviendao dao = new nhanviendao();
        try {
            if(dao.Sua(cn))
            {
                
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                clearform();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
     StringBuilder sb = new StringBuilder();
        if(txttimkiem.getText().equals("")){
             sb.append("id không được để trống \n");
        
        }else
        {
            txttimkiem.setBackground(Color.white);
        } 
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error" , JOptionPane.ERROR_MESSAGE);
        return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa hay không?","Hỏi",
        JOptionPane.YES_OPTION );
        if(choice == JOptionPane.NO_OPTION)
            return;
        CongNhanDao dao = new CongNhanDao();
      try {
          if(dao.xoa(txttimkiem.getText()))
          {
              loadTable();
              JOptionPane.showMessageDialog(this, "xóa thành công!");
              clearform();
          }
          else
          {
              JOptionPane.showMessageDialog(this, "xóa thất bại!");
          }
      } catch (Exception ex) {
          Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
         loadTable();
        try{
         nhanviendao dao = new nhanviendao();
         NhanVien cn = dao.findbyid(txttimkiem.getText());   
          if(cn!=null)
          {
               txthoten.setText(cn.getHoten());
                   txtngaysinh.setText(String.valueOf(cn.getNgaysinh()));
                   rbdnam.setSelected(cn.getGioitinh()==1?true:false);   
                   rbdnu.setSelected(cn.getGioitinh()==0?true:false); 
                   txtdiachi.setText(cn.getDiachi());
                   txtcongviec.setText(cn.getCongviec());
                   loadTable();
          }else
              JOptionPane.showMessageDialog(this, "không tìm thấy nhân viên nào có id là:"+ txttimkiem.getText());
            
            
            
     }catch(Exception e)
     {
         e.printStackTrace();
     }
               
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btntaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaomoiActionPerformed
    clearform();
    loadTable();
    }//GEN-LAST:event_btntaomoiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            if(row>=0)
            {
               String id = (String) jTable1.getValueAt(row, 0);
               nhanviendao dao = new nhanviendao();
               NhanVien cn = dao.findbyid(id);
               
               if(cn !=null)
               {
                   
                   txttimkiem.setText(String.valueOf(cn.getId()));
                   txthoten.setText(cn.getHoten());
                   txtngaysinh.setText(String.valueOf(cn.getNgaysinh()));
                   rbdnam.setSelected(cn.getGioitinh()==1?true:false);   
                   rbdnu.setSelected(cn.getGioitinh()==0?true:false); 
                   txtdiachi.setText(cn.getDiachi());
                   txtcongviec.setText(cn.getCongviec());
                   
                   
                   
               }
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntaomoi;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbdnam;
    private javax.swing.JRadioButton rbdnu;
    private javax.swing.JTextField txtcongviec;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtidchucvu;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
